version: "3.7"

services:
  flask:
    build: ./api
    #container_name: f_test
    restart: always
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    ports:
      - "8000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    ports:
      - "80:80"