version: "3.7"

services:
  client:
    build: ./Client
    #restart: always
    volumes:
      - ./Client:/Client
    ports:
      - "5000"
  user:
    build: ./User
    #restart: always
    volumes:
      - ./User:/User
    ports:
      - "5001"
  verify:
    build: ./Verify
    #restart: always
    volumes:
      - ./Verify:/Verify
    ports:
      - "5002"
  nginx:
    build: ./nginx
    #image: digiid.azurecr.io/nginxi
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client
      - user
      - verify
    ports:
      - "80:80"