version: "3.7"

services:
  client:
    build: ./Client
    ports:
      - "5001"

  user:
    build: ./User
    ports:
      - "5000"

  verify:
    build: ./Verify
    ports:
      - "5002"

  nginx:
    build: ./nginx
    depends_on:
      - client
      - user
      - verify
    ports:
      - "80:80"
      - "81:81"
      - "82:82"