apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: kaushikiyer/digi-id:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "50m"
          limits:
            cpu: "100m"

#Function: Deployment for the flask-app

# Command for auto scaling: kubectl autoscale deployment flask-app --cpu-percent=50 --min=1 --max=5
# Command for checking the status of the autoscaler: kubectl get hpa
# Command for checking the status of the pods: kubectl get pods
# Command for checking the status of the deployment: kubectl get deployment
# Command for checking the status of the service: kubectl get service
# Command for checking the status of the nodes: kubectl get nodes
